#!/usr/bin/env python3
"""Convert data/pokemon.csv into assets/data.js consumed by the site.

Only "real" Pokemon are kept: rows carrying an evolution_chain_id. The 90 rows
without one are alternate forms (mega evolutions, Rotom appliances, Pikachu
cosplay outfits...) which are not evolutions and would pollute the chains.
"""
import csv, json, pathlib

SRC = pathlib.Path(__file__).parent / "data" / "pokemon.csv"
OUT = pathlib.Path(__file__).parent / "assets" / "data.js"

STATS = ["hp", "attack", "defense", "special_attack", "special_defense", "speed"]

# Names the plain title-caser gets wrong.
DISPLAY = {
    "nidoran-f": "Nidoran♀", "nidoran-m": "Nidoran♂",
    "mr-mime": "Mr. Mime", "mime-jr": "Mime Jr.", "ho-oh": "Ho-Oh",
    "porygon-z": "Porygon-Z", "farfetchd": "Farfetch'd",
    "deoxys-normal": "Deoxys", "wormadam-plant": "Wormadam",
    "giratina-altered": "Giratina", "shaymin-land": "Shaymin",
    "basculin-red-striped": "Basculin", "darmanitan-standard": "Darmanitan",
    "tornadus-incarnate": "Tornadus", "thundurus-incarnate": "Thundurus",
    "landorus-incarnate": "Landorus", "keldeo-ordinary": "Keldeo",
    "meloetta-aria": "Meloetta", "meowstic-male": "Meowstic",
    "aegislash-shield": "Aegislash", "pumpkaboo-average": "Pumpkaboo",
    "gourgeist-average": "Gourgeist",
}


def blank(v):
    return v in ("NA", "", "None", None)


def clean(v):
    return None if blank(v) else v


def title(slug):
    if slug in DISPLAY:
        return DISPLAY[slug]
    return "-".join(w.capitalize() for w in slug.split("-"))


def ability(slug):
    """Ability slugs are hyphenated words, not hyphenated names: swift-swim -> Swift Swim."""
    return " ".join(w.capitalize() for w in slug.split("-"))


def main():
    rows = list(csv.DictReader(SRC.open()))
    kept = [r for r in rows if not blank(r["evolution_chain_id"])]

    out = []
    for r in kept:
        types = [r["type_1"]] + ([r["type_2"]] if not blank(r["type_2"]) else [])
        abilities = [a for a in (r["ability_1"], r["ability_2"]) if not blank(a)]
        out.append({
            "id": int(r["id"]),
            "slug": r["pokemon"],
            "name": title(r["pokemon"]),
            "types": types,
            "stats": {s: int(r[s]) for s in STATS},
            "bst": sum(int(r[s]) for s in STATS),
            "baseExp": None if blank(r["base_experience"]) else int(r["base_experience"]),
            "height": int(r["height"]),          # decimetres
            "weight": int(r["weight"]),          # hectograms
            "abilities": [ability(a) for a in abilities],
            "hidden": None if blank(r["ability_hidden"]) else ability(r["ability_hidden"]),
            "color": r["color_1"] if not blank(r["color_1"]) else "#888888",
            "color2": clean(r["color_2"]),
            "eggGroups": [g for g in (r["egg_group_1"], r["egg_group_2"]) if not blank(g)],
            "shape": clean(r["shape"]),
            "gen": int(r["generation_id"]),
            "chain": int(r["evolution_chain_id"]),
            "from": None if blank(r["evolves_from_species_id"]) else int(r["evolves_from_species_id"]),
            # url_image is a bare filename ("1.png"); 3 rows are NA but follow the
            # same id.png convention, so derive it and keep the site consistent.
            "img": r["url_image"] if not blank(r["url_image"]) else f"{r['id']}.png",
        })

    out.sort(key=lambda p: p["id"])
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text(
        "// Generated by build_data.py from data/pokemon.csv - do not edit by hand.\n"
        "window.POKEDEX = " + json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n"
    )
    evolving = sum(1 for p in out if any(q["from"] == p["id"] for q in out))
    print(f"wrote {OUT} - {len(out)} pokemon ({len(rows) - len(kept)} alt forms dropped), "
          f"{evolving} with at least one evolution")


if __name__ == "__main__":
    main()
